namespace Grl.App.Presentation;

public static class LiveErrorCatalog
{
    public static UiError For(string code) => code switch
    {
        "PREFLIGHT_BLOCKED" => new(code, "LIVE preflight blocked",
            "The app must be unelevated and the owned root must be an ordinary local directory on C:.",
            "Fix the root or launch unelevated, then retry."),
        "SIGNIN_DENIED" => new(code, "GitHub sign-in denied", "The device authorization was denied.",
            "Retry with a new code."),
        "SIGNIN_EXPIRED" => new(code, "GitHub code expired", "The device authorization expired.",
            "Retry with a new code."),
        "SIGNIN_WRONG_ACCOUNT" => new(code, "Wrong GitHub account",
            "The signed-in account does not match the exact target owner.", "Retry with the intended account."),
        "SIGNIN_NETWORK_ERROR" => new(code, "GitHub sign-in unavailable",
            "The sign-in request did not complete.", "Cancel and retry when GitHub is available."),
        "SCOPE_NO_ADMIN" => new(code, "Repository access blocked",
            "The exact target could not be confirmed with administrator permission.",
            "Check the App installation and repository administration permission."),
        "SCOPE_NOT_PRIVATE" => new(code, "Private repository required",
            "The exact target is public.", "Choose the approved private repository."),
        "LOCATION_NETWORK" => new(code, "Local root blocked",
            "The owned root is not an ordinary local C: directory.", "Choose an ordinary local root."),
        "INSTALL_DOWNLOAD_FAILED" => new(code, "Runner download failed",
            "The reviewed runner package was not installed.", "Inspect the safe local state before retrying."),
        "INSTALL_VERIFY_FAILED" => new(code, "Runner verification failed",
            "The reviewed package verification did not pass.", "Do not use the runner files; inspect the local state."),
        "INSTALL_EXTRACT_FAILED" => new(code, "Runner CLI verification failed",
            "The installed runner CLI did not pass the read-only contract probe.", "Inspect the installed package."),
        "INSTALL_CONFIGURE_FAILED" => new(code, "Runner setup incomplete",
            "Configuration or portable start did not complete. Registration may need explicit cleanup.",
            "If a process is owned, Stop Now may cancel work. Otherwise use exact-identity recovery; leave pending state if uncertain."),
        "RECOVERY_REQUIRED" => new(code, "Existing runner root requires recovery",
            "An existing runner root was found. No download, configure, or process attach was attempted.",
            "After confirming this repository, use exact-identity recovery or leave the root untouched."),
        "RECOVERY_STATE_UNAVAILABLE" => new(code, "Existing runner root cannot be trusted for recovery",
            "Recovery evidence is missing, corrupt, in use, or has a different identity. No installation was attempted.",
            "Leave the root untouched and inspect the local and remote runner state manually."),
        "RECOVERY_COMPLETED" => new(code, "Prior removal recorded",
            "The existing root records an earlier verified remote removal. No new remote check or installation was attempted.",
            "Leave the root untouched for inspection; a new activation needs a separate reviewed procedure."),
        "RUNNER_DEGRADED" => new(code, "Runner degraded",
            "The runner operation did not complete or its status is uncertain. A process may still be active.",
            "Use explicit Stop Now only if this window owns the process; then recover the exact registration."),
        "RUNNER_VERSION_UNSUPPORTED" => new(code, "Runner version changed",
            "The runner CLI could not be re-verified at the reviewed version immediately before start. It may have self-updated.",
            "Do not start this runner with assumed metadata. Update the wizard or restore a reviewed supported runner package."),
        "DISCONNECT_REMOTE_UNAVAILABLE" => new(code, "Runner status unavailable",
            "GitHub runner status or remote removal could not be verified because the remote operation was unavailable.",
            "Retry only after GitHub connectivity is restored; do not assume the runner is removed."),
        "DISCONNECT_IDENTITY_BLOCKED" => new(code, "Exact runner identity is not safely removable",
            "No unique exact-name offline and non-busy runner could be proven. Blind retries cannot make this evidence safe.",
            "Do not keep retrying. After independently confirming no runner listener or job is active, inspect the exact runner in repository Settings > Actions > Runners and remove it manually if appropriate."),
        "DISCONNECT_PROCESS_UNCERTAIN" => new(code, "A runner process may still exist",
            "The wizard cannot prove that no listener from this or an earlier session is still running.",
            "Do not remove or kill a potentially active job. Independently confirm the listener is stopped first, then inspect the exact runner in repository Settings > Actions > Runners."),
        "INVALID_TRANSITION" => new(code, "Action unavailable",
            "This action is unavailable in the current live state.", "Choose an enabled action."),
        _ => new(code, "LIVE action stopped", "The operation did not complete.",
            "Inspect the safe status and retry explicitly.")
    };
}
